-- -------------------------------------------------------------------------
-- FIX CONTACT FORM TIMEOUT (Missing RLS Policies)
-- -------------------------------------------------------------------------

-- 1. Ensure the table exists (it should, but safety first)
CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow ANYONE to insert messages (Public Contact Form)
DROP POLICY IF EXISTS "Anyone can send messages" ON contact_messages;
CREATE POLICY "Anyone can send messages"
ON contact_messages
FOR INSERT
TO public
WITH CHECK (true);

-- 4. Policy: Allow Admins to View Messages
DROP POLICY IF EXISTS "Admins can view messages" ON contact_messages;
CREATE POLICY "Admins can view messages"
ON contact_messages
FOR SELECT
TO authenticated
USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin' OR
  auth.email() = 'lovejeet1225@gmail.com'
);

-- 5. Policy: Allow Admins to Delete Messages
DROP POLICY IF EXISTS "Admins can delete messages" ON contact_messages;
CREATE POLICY "Admins can delete messages"
ON contact_messages
FOR DELETE
TO authenticated
USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin' OR
  auth.email() = 'lovejeet1225@gmail.com'
);
